# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import random as rd

Digit_list = [[rd.randint(1, 200), rd.randint(1, 200), rd.randint(1, 200)] for i in range(10)]

class Trapezoid:
    def __init__(self, parameters):
        self.param1 = parameters[0]
        self.param2 = parameters[1]
        self.param3 = parameters[2]
    def __str__(self):
        return str(self.param1)+" "+str(self.param2)+" "+ str(self.param3)
    def area(self):
        return (self.param1 + self.param2) / 2 * self.param3
    def __le__(self, concurent):
        return self.area() <= concurent.area()
    def __eq__(self, concurent):
        return self.area() == concurent.area()


class Rectangle(Trapezoid):
    def __init__(self, parameters):
        super().__init__(parameters)
        self.height=None
    def __str__(self):
        return str(self.param1)+" "+ str(self.param2)
    def area(self):
        return self.param1 * self.param2


class Square(Rectangle):
    def __init__(self, parameters):
        super().__init__(parameters)
        self.param2=None
    def __str__(self):
        return str(self.param1)
    def area(self):
       return self.param1**2
       





    


class Ui_MainWindow(object):
    trapezoid=Trapezoid(Digit_list[0])
    rectangle=Rectangle(Digit_list[0])
    square=Square(Digit_list[0])
    nowIsShown = ''
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.areabutton = QtWidgets.QPushButton(self.centralwidget)
        self.areabutton.setGeometry(QtCore.QRect(50, 340, 281, 61))
        self.areabutton.setObjectName("areabutton")
        self.areabutton.clicked.connect(self.open_dialog)
        self.areashow = QtWidgets.QLabel(self.centralwidget)
        self.areashow.setGeometry(QtCore.QRect(410, 350, 400, 13))
        self.areashow.setObjectName("areashow")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(30, 30, 731, 261))
        self.img.setText("")
        self.img.setObjectName("img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menushape = QtWidgets.QMenu(self.menubar)
        self.menushape.setObjectName("menushape")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionrectangle = QtWidgets.QAction(MainWindow)
        self.actionrectangle.setObjectName("actionrectangle")
        self.actionsquare = QtWidgets.QAction(MainWindow)
        self.actionsquare.setObjectName("actionsquare")
        self.actiontrapezoid = QtWidgets.QAction(MainWindow)
        self.actiontrapezoid.setObjectName("actiontrapezoid")
        self.menushape.addAction(self.actionrectangle)
        self.menushape.addAction(self.actionsquare)
        self.menushape.addAction(self.actiontrapezoid)
        self.menubar.addAction(self.menushape.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionrectangle.triggered.connect(lambda: self.showShape("rectangle.png"))
        self.actionsquare.triggered.connect(lambda: self.showShape("square.png"))
        self.actiontrapezoid.triggered.connect(lambda: self.showShape("trapezoid.png"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.areabutton.setText(_translate("MainWindow", "calculate area"))
        self.areashow.setText(_translate("MainWindow", "area is: "))
        self.menushape.setTitle(_translate("MainWindow", "shape"))
        self.actionrectangle.setText(_translate("MainWindow", "rectangle"))
        self.actionsquare.setText(_translate("MainWindow", "square"))
        self.actiontrapezoid.setText(_translate("MainWindow", "trapezoid"))
    
    def open_dialog(self):
            msg = QMessageBox()
            msg.setWindowTitle("actions")
            msg.setText("You are about to calculate area")
            msg.setIcon(QMessageBox.Question)
            msg.setStandardButtons(QMessageBox.Close|QMessageBox.Retry|QMessageBox.Ignore)
            msg.setInformativeText("If i were you, i would do it")
            yes_button = msg.addButton("Calculate!", QtWidgets.QMessageBox.YesRole)
            msg.setDefaultButton(yes_button)
            yes_button.clicked.disconnect()
            yes_button.clicked.connect(self.calculateArea)
            msg.exec_()
           

    def calculateArea(self):
        if self.nowIsShown == "rectangle.png":
            self.areashow.setText("rectangle area is: "+ str(self.rectangle.area()))
        if self.nowIsShown == "square.png":
            self.areashow.setText("square area is: "+ str(self.square.area()))
        if self.nowIsShown == "trapezoid.png":
            self.areashow.setText("trapezoid area is: "+ str(self.trapezoid.area()))

    def showShape(self, path):
        self.img.setPixmap(QtGui.QPixmap(path))
        self.nowIsShown = path

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
